# Generated by Django 6.0.6 on 2026-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='URL-слаг'),
        ),
    ]
