# Generated by Django 6.0.6 on 2026-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.CharField(blank=True, max_length=300, verbose_name='Специализация'),
        ),
    ]
