# Generated by Django 6.0.6 on 2026-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_is_paid_booking_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('organizer', 'Организатором'), ('supplier', 'Поставщиком')], max_length=20, null=True, verbose_name='Кем отменено'),
        ),
    ]
